### ISSUE TITLE
 "Too many open files" when reset the Scrimmage environment in a loop

### ISSUE THREAD

**Issue by jennytran158** [gtri/scrimmage#388]
Answer the following questions:

* what are you trying to do?
    Implement RL using Scrimmage env
* what is the problem and how can it be recreated?
    I got this error "Too many open files" when I reset the environment in a loop.  The first few iterations of the loop runs fine, but after a while this error occurs
  
  
Traceback (most recent call last):
  File "/Users/tramtran/Library/Python/3.6/lib/python/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'scrimmage-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_openai.py", line 94, in test_openai
    env = gym.make('scrimmage-v0')
  File "/Users/tramtran/Library/Python/3.6/lib/python/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/Users/tramtran/Library/Python/3.6/lib/python/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/Users/tramtran/Library/Python/3.6/lib/python/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: scrimmage-v0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_openai.py", line 207, in <module>
    test_openai()
  File "test_openai.py", line 189, in test_openai
    temp_obs = copy.deepcopy(env.reset())
  File "/Users/tramtran/Library/Python/3.6/lib/python/site-packages/gym/wrappers/time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
RuntimeError: filesystem::recursive_directory_iterator directory error: Too many open files
* what scrimmage commit are you on? You can see this with `git rev-parse HEAD`
26bebb70fd8e5805f558db22a275bffc41946811
* describe any changes you made to scrimmage.
Change the code in my_openai.py from the tutorial https://www.scrimmagesim.org/sphinx/html/tutorials/openai-plugin.html
to 
       `obs = []

        temp_obs = copy.deepcopy(env.reset())
        obs.append(temp_obs)
        total_reward = 0
        for _ in range(num_iterations):
            temp_obs = copy.deepcopy(env.reset())
            for i in range(200):
                action = get_action(temp_obs)
                temp_obs, reward, done = env.step(action)[:3]
                obs.append(copy.deepcopy(temp_obs))
                total_reward += reward
                print("Total Reward: ")
                print(total_reward)
                print("\n")
                if done:
                    break`
* If you can recreate the issue using only plugins in the scrimmage repository, what mission file are you running?
I'm using my mission file

**Comment by hychong1997** [comment]
Hi! Have you ever fixed the problem?
