### ISSUE TITLE
OpenAI confuse

### ISSUE THREAD

**Issue by luanyun** [gtri/scrimmage#39]
Today When trying to Install SCRIMMAGE Python Bindings and Create an OpenAI Plugin follow the tutorial.

when running the /path/to/scrimmage/python/test/test_openai.py, An error come 
 "AttributeError: 'ScrimmageEnv' object has no attribute '_render'"

when running the created test_openai.py referred by the tutorial, I cannot make the environment

Failed to open autonomy plugin: SimpleLearner
Failed to parse entity at start position: x=0, y=0
Failed to generate entity
[>                                                                     ] 0 %
End of Simulation: No Entities Remaining

Simulation Complete
Traceback (most recent call last):
  File "/home/lht/scrimmage/my-scrimmage-plugins/test/test_openai.py", line 39, in <module>
    test_openai()
  File "/home/lht/scrimmage/my-scrimmage-plugins/test/test_openai.py", line 21, in test_openai
    env = gym.make('scrimmage-v0')
  File "/home/lht/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/lht/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/lht/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/lht/scrimmage/scrimmage/python/scrimmage/external_control.py", line 101, in __init__
    [self.queues[i]['env'].get() for i in range(num_actors)]
  File "/home/lht/scrimmage/scrimmage/python/scrimmage/external_control.py", line 101, in <listcomp>
    [self.queues[i]['env'].get() for i in range(num_actors)]
  File "/home/lht/anaconda3/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/lht/anaconda3/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()

**Comment by luanyun** [comment]
have been solved.
for the first,  /path/to/scrimmage/python/scrimmage/external_control.py should be fixed by 'render'->'_render' in Ln 183
the second is for my fault. I forgot to register the plugin in src file.

**Comment by esquires** [comment]
Thanks. This has been fixed in commit 8301bf9
