### ISSUE TITLE
A problem about OpenAI!

### ISSUE THREAD

**Issue by hychong1997** [gtri/scrimmage#534]
Hi!
I am trying to use the OpenAI following the procedure on https://www.scrimmagesim.org/sphinx/html/tutorials/openai-plugin.html.
I use Ubuntu 18.04. At of the files are built successfully.
However when i ran "python my_openai.py", it showed :
Traceback (most recent call last):
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'scrimmage-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my_openai.py", line 16, in test_openai
    env = gym.make('scrimmage-v0')
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: scrimmage-v0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my_openai.py", line 52, in <module>
    test_openai()
  File "my_openai.py", line 28, in test_openai
    env = gym.make('scrimmage-v0')
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/hyc/scrimmage/scrimmage/env/lib/python3.6/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. scrimmage.bindings.py_bindings.ScrimmageOpenAIEnv(mission_file: str, combine_actors: bool=False, global_sensor: bool=False, static_obs_space: bool=True, timestep: float=-1)

Invoked with: kwargs: enable_gui=False, mission_file='/home/hyc/scrimmage/my-scrimmage-plugins/missions/openai_mission.xml'

Could you give me any suggestions and instructions. 
Sincerely.

**Comment by frazierbaker** [comment]
I haven't seen this error before, but I'm happy to make some suggestions.  Have you tried removing `enable_gui=False`?  It doesn't seem to be listed in the TypeError.  Also, can you tell me what version of `gym` you're using in case this is something we need to update to work with a newer version of OpenAI Gym.
